# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "旅"


author:
  name:             Sd.Invol
  facebook:         your-id
  twitter:          your-id
  github:           sd-invol
  linkedin:         your-id
  medium:           your-id
  tumblr:           your-id
  email:            sd.invol@gmail.com

math:
  mathjax:          true
  katex:            false

# Google-analytics
google-analytics:
  id:               "sd.invol"

# Disqus
disqus:
  id:               "sd-invol"

# URL
url:                "https://sd-invol.github.io"
#url:               "localhost:4000"
baseurl:            ""


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Shanghai
permalink:          /:year/:month/:day/:title/

# Pagination
paginate:           6
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "TopCoder"
    url:            "/topcoder"
  - name:           "wiki"
    url:            "https://wiki.icpc-camp.org/twsf/Front Page.html"
  - name:           "Github"
    url:            "https://github.com/sd-invol"


# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
